---
abstract: 'Conditional preservation of whitespace while parsing'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: '0.94'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MarpaX-Demo-StringParser
provides:
  MarpaX::Demo::StringParser:
    file: lib/MarpaX/Demo/StringParser.pm
    version: '2.01'
  MarpaX::Demo::StringParser::Config:
    file: lib/MarpaX/Demo/StringParser/Config.pm
    version: '2.01'
  MarpaX::Demo::StringParser::Filer:
    file: lib/MarpaX/Demo/StringParser/Filer.pm
    version: '2.01'
  MarpaX::Demo::StringParser::Renderer:
    file: lib/MarpaX/Demo/StringParser/Renderer.pm
    version: '2.01'
  MarpaX::Demo::StringParser::Utils:
    file: lib/MarpaX/Demo/StringParser/Utils.pm
    version: '2.01'
requires:
  Capture::Tiny: '0.11'
  Config: '0'
  Config::Tiny: '2.14'
  Date::Simple: '3.03'
  File::Basename: '2.78'
  File::Copy: '2.21'
  File::HomeDir: '0.99'
  File::Slurp: '9999.19'
  File::Spec: '3.33'
  Getopt::Long: '2.38'
  GraphViz2: '2.33'
  HTML::Entities::Interpolate: '1.04'
  Log::Handler: '0.82'
  Marpa::R2: '2.096'
  Moo: '1.002'
  Path::Tiny: '0.025'
  Pod::Usage: '1.36'
  Set::Array: '0.23'
  Text::CSV: '1.32'
  Text::CSV::Slurp: '1.01'
  Text::Xslate: '1.4001'
  Tree::DAG_Node: '1.22'
  Try::Tiny: '0.09'
  Types::Standard: '1.000004'
  charnames: '0'
  open: '0'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  license: http://opensource.org/licenses/artistic-license-2.0.php
  repository: https://github.com/ronsavage/MarpaX-Demo-StringParser
version: '2.01'
